services:
  app:
    build:
      context: .
      target: build
    container_name: callab_app
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b 0.0.0.0 -p 3000"
    volumes:
      - .:/app
      - .:/rails
      - bundle_cache:/usr/local/bundle
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      RAILS_ENV: development
      DATABASE_HOST: db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      DATABASE_NAME: callab_development
      BUNDLE_PATH: /usr/local/bundle
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
      OLLAMA_HOST: ${OLLAMA_HOST}
      TWILIO_ACCOUNT_SID: ${TWILIO_ACCOUNT_SID}
      TWILIO_AUTH_TOKEN: ${TWILIO_AUTH_TOKEN}
      TWILIO_PHONE_NUMBER: ${TWILIO_PHONE_NUMBER}
      TWILIO_MESSAGING_SERVICE_SID: ${TWILIO_MESSAGING_SERVICE_SID}
      SMTP_ADDRESS: ${SMTP_ADDRESS}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_DOMAIN: ${SMTP_DOMAIN}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_FROM_EMAIL: ${SMTP_FROM_EMAIL}
    depends_on:
      - db
    stdin_open: true
    tty: true


  db:
    image: pgvector/pgvector:pg16
    container_name: callab_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: callab_development
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  # Optional: Redis for ActiveJob / Sidekiq later
  redis:
    image: redis:7-alpine
    container_name: callab_redis
    ports:
      - "6379:6379"

volumes:
  db_data:
  bundle_cache:

